"""
Geometric Spatial Delay Model for Co-Translational GFP Folding
==============================================================

Models co-translational folding as a spatial race along the mRNA.  Each
GFP domain requires a minimum "folding distance" (L_fold = tau_fold × v)
of continued translation after it emerges from the ribosome exit tunnel.
If the remaining transcript is shorter than this distance, the domain
cannot fold co-translationally.

Assuming ribosomes are uniformly distributed along the transcript in
steady state, the detection probability for domain i is:

    P_i = max(0, (L_total - x_fluorescent_i) / L_total)

where x_fluorescent_i = x_exit_i + L_fold.

Two fitted parameters per GFP variant:
    A        – Maximum amplitude (detection/competence fraction, %)
    tau_fold – Inherent folding time (seconds)

Inputs:
    - Per-cell CoF efficiency data from Excel (data/ directory)

Outputs:
    - Fit results and spatial constraints (CSV + JSON)
    - Model fit plots (PNG + SVG)
    - 2D parameter sensitivity heatmaps (PNG + SVG)
"""

import re
import csv
import json
import numpy as np
import pandas as pd
from scipy import stats
from scipy.optimize import minimize
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from pathlib import Path


# =============================================================================
# DIRECTORIES
# =============================================================================
output_dir = Path(__file__).resolve().parent.parent  # simple_model_gm_4x_ke/
figures_dir = output_dir / 'figures'
data_dir = output_dir / 'databases'
figures_dir.mkdir(exist_ok=True)
data_dir.mkdir(exist_ok=True)


# =============================================================================
# CONSTRUCT GEOMETRY (loaded from GFP_positions.csv)
# =============================================================================
# GFP_positions.csv is generated by the GFP_positions.ipynb notebook, which
# parses actual plasmid .dna sequence files to locate the LEFVTAA motif
# (GFP C-terminal tag) and computes domain-end and exit-tunnel positions.
# The last domain's exit position is capped at gene_length (= stop codon).
_pos_df = pd.read_csv(data_dir / 'GFP_positions.csv')
X_END = _pos_df['GFP_tag_position_end'].tolist()               # [590, 835, ..., 1815]
X_EXIT = _pos_df['GFP_tag_position_end_plus_exit_tunnel'].tolist()  # [640, 885, ..., 1826]
N_GFP_MAX = len(X_END)

# The last exit position is capped at gene_length (stop codon) = L_TOTAL
L_TOTAL = X_EXIT[-1]    # 1826 aa (protein + stop codon)
L_TUNNEL = 50           # Ribosome exit tunnel length (amino acids)

# Average elongation rates (aa/s) — from Harringtonine run-off assays
# on 10×HA–4×GFP(sf or uv)–2×mCherry constructs
V_SF = 3.88     # GFPfast
V_UV = 1.63     # GFPslow


# =============================================================================
# DATA LOADING
# =============================================================================
def load_experimental_data(filepath):
    """
    Load per-cell CoF efficiency values from Excel and compute summary
    statistics (mean, SEM) for each GFP copy-number group.

    The Excel files follow a structured layout:
        Row 0: Title
        Row 1: Dates
        Row 2: Reporter variant names (e.g., "pUB-RBsmHA-3xsfGFP-3xmCh-24xMS2")
        Row 3: (blank)
        Row 4: Header row containing "ML 0.5" column markers
        Row 5+: Per-cell efficiency values

    The GFP copy number is extracted from the reporter name via regex.

    Parameters
    ----------
    filepath : str or Path
        Path to the Excel file.

    Returns
    -------
    means : dict[int, float]
        Mean CoF efficiency (%) per GFP copy number.
    sems : dict[int, float]
        Standard error of the mean per GFP copy number.
    cell_data : dict[int, np.ndarray]
        Per-cell values per GFP copy number (for scatter plots).
    """
    df = pd.read_excel(filepath, header=None)

    # Locate the header row (contains 'ML 0.5' marker)
    header_row = None
    for r in range(min(10, df.shape[0])):
        for c in range(df.shape[1]):
            cell_val = str(df.iloc[r, c]) if pd.notna(df.iloc[r, c]) else ''
            if 'ML 0.5' in cell_val:
                header_row = r
                break
        if header_row is not None:
            break
    if header_row is None:
        raise ValueError(f"Could not find 'ML 0.5' header row in {filepath}")

    # Locate the reporter annotation row (above the header)
    reporter_row = None
    for r in range(header_row - 1, -1, -1):
        for c in range(1, df.shape[1]):
            cell_val = str(df.iloc[r, c]) if pd.notna(df.iloc[r, c]) else ''
            if 'sfGFP' in cell_val or 'GFPuv' in cell_val or 'GFP' in cell_val:
                reporter_row = r
                break
        if reporter_row is not None:
            break
    if reporter_row is None:
        raise ValueError(f"Could not find reporter row in {filepath}")

    # Extract per-cell values, grouped by GFP copy number
    raw_data = {}
    for col in range(1, df.shape[1]):
        header = str(df.iloc[header_row, col]) if pd.notna(df.iloc[header_row, col]) else ''
        if 'ML 0.5' not in header:
            continue

        reporter = str(df.iloc[reporter_row, col]) if pd.notna(df.iloc[reporter_row, col]) else ''
        match = re.search(r'(\d+)x(?:sf)?GFP', reporter, re.IGNORECASE)
        if match:
            n_gfp = int(match.group(1))
        else:
            continue

        col_vals = df.iloc[header_row + 1:, col].dropna()
        for val in col_vals:
            if isinstance(val, (int, float)) and val > 0:
                raw_data.setdefault(n_gfp, []).append(float(val))

    # Compute summary statistics
    means = {}
    sems = {}
    cell_data = {}
    for n in sorted(raw_data.keys()):
        arr = np.array(raw_data[n])
        means[n] = float(np.mean(arr))
        sems[n] = float(stats.sem(arr))
        cell_data[n] = arr

    return means, sems, cell_data


# =============================================================================
# MODEL
# =============================================================================
def geometric_delay_model(n_gfp, tau_fold, A, v):
    """
    Geometric Spatial Delay Model.

    For each GFP domain i (0-indexed up to n_gfp-1):
      1. Folding distance:  L_fold = tau_fold × v
      2. Fluorescence onset: x_fluorescent = x_exit[i] + L_fold
      3. Detection probability (uniform ribosome distribution):
           P_i = max(0, (L_total - x_fluorescent) / L_total)
      4. Total efficiency = A × Σ P_i

    Parameters
    ----------
    n_gfp : int
        Number of GFP domains in the construct (1–6).
    tau_fold : float
        Inherent folding time (seconds).
    A : float
        Maximum amplitude / detection fraction (%).
    v : float
        Elongation rate (aa/s).

    Returns
    -------
    float
        Predicted CoF efficiency (%).
    """
    L_fold = tau_fold * v
    signal = 0.0
    for i in range(n_gfp):
        x_fluorescent = X_EXIT[i] + L_fold
        if x_fluorescent < L_TOTAL:
            signal += (L_TOTAL - x_fluorescent) / L_TOTAL
    return A * signal


def compute_chi2(A, tau_fold, v, data_means, data_sems):
    """
    SEM-weighted χ² between model predictions and experimental data.

    χ² = Σ_n [(predicted(n) - observed(n)) / SEM(n)]²
    """
    n_vals = list(data_means.keys())
    obs = np.array(list(data_means.values()))
    sem = np.array(list(data_sems.values()))
    preds = np.array([geometric_delay_model(n, tau_fold, A, v) for n in n_vals])
    return float(np.sum(((preds - obs) / sem) ** 2))


# =============================================================================
# FITTING
# =============================================================================
def fit_model(data_means, data_sems, v, variant_name):
    """
    Fit the geometric model to experimental CoF efficiency data.

    Minimizes SEM-weighted χ² over (A, tau_fold) using L-BFGS-B.

    Returns
    -------
    dict
        Fit results including optimal parameters, predictions, and
        goodness-of-fit metrics (R², χ²).
    """
    n_vals = list(data_means.keys())
    obs_vals = np.array(list(data_means.values()))

    # Minimize SEM-weighted χ²
    def objective(params):
        A, tau_fold = params
        return compute_chi2(A, tau_fold, v, data_means, data_sems)

    res = minimize(objective, [50, 100], bounds=[(0, 100), (0, 1000)],
                   method='L-BFGS-B')
    A_opt, tau_opt = res.x

    # Compute predictions and goodness-of-fit
    preds = np.array([geometric_delay_model(n, tau_opt, A_opt, v) for n in n_vals])
    ss_res = np.sum((preds - obs_vals) ** 2)
    ss_tot = np.sum((obs_vals - np.mean(obs_vals)) ** 2)
    r2 = 1.0 - ss_res / ss_tot
    L_fold = tau_opt * v

    # Report
    print(f"\n--- {variant_name} Geometric Fit ---")
    print(f"  Amplitude (A) = {A_opt:.1f}%")
    print(f"  Folding Time (tau_fold) = {tau_opt:.1f} s")
    print(f"  Folding Distance (L_fold) = {L_fold:.0f} aa")
    print(f"  R² = {r2:.3f}, χ² = {res.fun:.2f}")
    for n, p in zip(n_vals, preds):
        print(f"    {n}×GFP: Observed = {data_means[n]:.1f}%, "
              f"Predicted = {p:.1f}%, Residual = {p - data_means[n]:+.1f}%")

    return {
        'variant': variant_name,
        'A': A_opt,
        'tau_fold': tau_opt,
        'L_fold': L_fold,
        'v': v,
        'r2': r2,
        'chi2': res.fun,
        'n_vals': n_vals,
        'obs': obs_vals.tolist(),
        'sems': list(data_sems.values()),
        'preds': preds.tolist(),
    }


# =============================================================================
# SENSITIVITY ANALYSIS
# =============================================================================
def compute_chi2_grid(tau_range, A_range, v, data_means, data_sems):
    """
    Evaluate χ² on a 2D grid over (τ_fold, A) parameter space.

    Returns
    -------
    np.ndarray
        Shape (len(A_range), len(tau_range)) — rows index A, columns τ_fold.
    """
    grid = np.zeros((len(A_range), len(tau_range)))
    for i, A in enumerate(A_range):
        for j, tau in enumerate(tau_range):
            grid[i, j] = compute_chi2(A, tau, v, data_means, data_sems)
    return grid


def plot_sensitivity(result_sf, result_uv,
                     sf_means, sf_sems, uv_means, uv_sems,
                     save_name='sensitivity_geometric_2d'):
    """
    Plot 2D χ² parameter-space heatmaps for both GFP variants.

    Each panel shows the χ² landscape as a function of τ_fold (x-axis)
    and A (y-axis), with the optimum marked by a red star and the 95%
    confidence contour (Δχ² = 5.99 for 2 parameters) drawn in red dashes.
    """
    N_GRID = 200

    configs = [
        {
            'result': result_sf,
            'tau_range': np.linspace(20, 300, N_GRID),
            'A_range': np.linspace(0, 100, N_GRID),
            'v': V_SF,
            'means': sf_means,
            'sems': sf_sems,
            'title': r'dGFP$_{\mathrm{Fast}}$',
        },
        {
            'result': result_uv,
            'tau_range': np.linspace(50, 800, N_GRID),
            'A_range': np.linspace(0, 100, N_GRID),
            'v': V_UV,
            'means': uv_means,
            'sems': uv_sems,
            'title': r'dGFP$_{\mathrm{Slow}}$',
        },
    ]

    fig, axes = plt.subplots(1, 2, figsize=(12, 4.5))
    ci_results = {}

    for ax, cfg, label in zip(axes, configs, ['A', 'B']):
        r = cfg['result']
        chi2_grid = compute_chi2_grid(
            cfg['tau_range'], cfg['A_range'], cfg['v'],
            cfg['means'], cfg['sems'],
        )

        # Cache grid for individual panel plotting
        cfg['chi2_grid'] = chi2_grid

        # Extract 95% CI bounds (Δχ² ≤ 5.99 for 2 free parameters)
        threshold = r['chi2'] + 5.99
        mask = chi2_grid <= threshold
        tau_in_ci = cfg['tau_range'][np.any(mask, axis=0)]
        A_in_ci = cfg['A_range'][np.any(mask, axis=1)]
        ci_results[cfg['title']] = {
            'tau_fold_opt': r['tau_fold'],
            'A_opt': r['A'],
            'chi2': r['chi2'],
            'L_fold': r['L_fold'],
            'v': cfg['v'],
            'tau_fold_95ci_low': float(tau_in_ci.min()),
            'tau_fold_95ci_high': float(tau_in_ci.max()),
            'A_95ci_low': float(A_in_ci.min()),
            'A_95ci_high': float(A_in_ci.max()),
        }
        print(f"\n  {cfg['title']} 95% CI (Δχ² ≤ 5.99):")
        print(f"    τ_fold: [{tau_in_ci.min():.1f}, {tau_in_ci.max():.1f}] s  (optimum: {r['tau_fold']:.1f} s)")
        print(f"    A:      [{A_in_ci.min():.1f}, {A_in_ci.max():.1f}] %  (optimum: {r['A']:.1f} %)")

        # Contour-filled heatmap (clip to 95th percentile for colorbar)
        vmax = np.percentile(chi2_grid, 95)
        levels = np.linspace(0, vmax, 20)
        cf = ax.contourf(cfg['tau_range'], cfg['A_range'], chi2_grid,
                         levels=levels, cmap='viridis_r', extend='max')
        ax.contour(cfg['tau_range'], cfg['A_range'], chi2_grid,
                   levels=levels, colors='black', linewidths=0.3, alpha=0.4)

        # 95% CI contour (Δχ² = 5.99 for 2 free parameters)
        ax.contour(cfg['tau_range'], cfg['A_range'], chi2_grid,
                   levels=[r['chi2'] + 5.99],
                   colors='red', linewidths=2.0, linestyles='--')

        # Mark optimum
        ax.plot(r['tau_fold'], r['A'], marker='*', color='red', markersize=18,
                markeredgecolor='white', markeredgewidth=1.0, zorder=5)

        # Labels
        cbar = fig.colorbar(cf, ax=ax, shrink=0.9)
        cbar.set_label(r'$\chi^2$', fontsize=14)
        ax.set_xlabel(r'$\tau_{\mathrm{fold}}$ (s)', fontsize=15)
        ax.set_ylabel(r'$A$ (%)', fontsize=15)
        ax.set_title(cfg['title'], fontsize=14, fontweight='bold', pad=10)
        ax.tick_params(axis='both', labelsize=12)

        # Panel label
        ax.text(-0.12, 1.05, label, transform=ax.transAxes,
                fontsize=18, fontweight='bold', va='bottom', ha='left')

    plt.tight_layout()
    for fmt in ['png', 'svg']:
        fig.savefig(figures_dir / f'{save_name}.{fmt}', dpi=300,
                    bbox_inches='tight', facecolor='white', format=fmt)
    plt.close(fig)
    print(f"Saved: figures/{save_name}.png + .svg")

    # Save individual panels as separate files
    for cfg in configs:
        r = cfg['result']
        chi2_grid = cfg['chi2_grid']
        suffix = 'fast' if 'Fast' in cfg['title'] else 'slow'

        fig_ind, ax = plt.subplots(figsize=(6, 5))

        vmax = np.percentile(chi2_grid, 95)
        levels = np.linspace(0, vmax, 20)
        cf = ax.contourf(cfg['tau_range'], cfg['A_range'], chi2_grid,
                         levels=levels, cmap='viridis_r', extend='max')
        ax.contour(cfg['tau_range'], cfg['A_range'], chi2_grid,
                   levels=levels, colors='black', linewidths=0.3, alpha=0.4)

        ax.contour(cfg['tau_range'], cfg['A_range'], chi2_grid,
                   levels=[r['chi2'] + 5.99],
                   colors='red', linewidths=2.0, linestyles='--')

        ax.plot(r['tau_fold'], r['A'], marker='*', color='red', markersize=18,
                markeredgecolor='white', markeredgewidth=1.0, zorder=5)

        cbar = fig_ind.colorbar(cf, ax=ax, shrink=0.9)
        cbar.set_label(r'$\chi^2$', fontsize=20, color='black')
        # Colorbar with only min, middle, max ticks
        vmax_round = int(np.ceil(vmax / 1000) * 1000)
        cbar_ticks = [0, vmax_round // 2, vmax_round]
        cbar.set_ticks(cbar_ticks)
        cbar.set_ticklabels([str(t) for t in cbar_ticks])
        cbar.ax.tick_params(labelsize=14, labelcolor='black')
        ax.set_xlabel(r'$\tau_{\mathrm{fold}}$ (s)', fontsize=22, color='black')
        ax.set_ylabel(r'$A$ (%)', fontsize=22, color='black')
        ax.set_title(cfg['title'], fontsize=22, pad=12, color='black')
        ax.tick_params(axis='both', labelsize=20, colors='black')

        plt.tight_layout()
        for fmt in ['png', 'svg']:
            fig_ind.savefig(figures_dir / f'sensitivity_geometric_{suffix}.{fmt}',
                            dpi=300, bbox_inches='tight', facecolor='white',
                            format=fmt)
        plt.close(fig_ind)
        print(f"Saved: figures/sensitivity_geometric_{suffix}.png + .svg")

    return ci_results


# =============================================================================
# PLOTTING — Model Fit
# =============================================================================
# Global Matplotlib style
plt.rcParams.update({
    'font.family': 'Arial',
    'font.size': 12,
    'text.color': 'black',
    'axes.labelcolor': 'black',
    'axes.edgecolor': 'black',
    'xtick.color': 'black',
    'ytick.color': 'black',
    'legend.edgecolor': 'black',
    'axes.spines.top': True,
    'axes.spines.right': True,
    'axes.spines.bottom': True,
    'axes.spines.left': True,
    'axes.facecolor': 'white',
    'figure.facecolor': 'white',
    'savefig.facecolor': 'white',
    'axes.grid': False,
})


def plot_geometric_fit(result, cell_data, save_name, label, ylim=100):
    """Plot geometric model fit with per-cell scatter and model predictions."""
    fig, ax = plt.subplots(figsize=(5, 5))

    # Categorical x positions (evenly spaced, no gap for missing constructs)
    n_vals = sorted(result['n_vals'])
    x_pos = list(range(1, len(n_vals) + 1))
    n_to_x = {n: x for n, x in zip(n_vals, x_pos)}

    obs = list(result['obs'])
    sem = list(result['sems'])
    preds = list(result['preds'])

    # Per-cell data points with jitter
    np.random.seed(42)
    for n in n_vals:
        if n in cell_data and len(cell_data[n]) > 0:
            jitter = np.random.normal(0, 0.05, len(cell_data[n]))
            ax.scatter([n_to_x[n] + j for j in jitter], cell_data[n],
                       alpha=0.35, color='darkgray', s=18, zorder=1)

    # Mean ± SEM
    ax.errorbar(x_pos, obs, yerr=sem, fmt='o', capsize=5, capthick=2,
                color='dimgray', markersize=10, label='Data (mean ± SEM)',
                zorder=3, linewidth=2)

    # Model predictions
    ax.scatter(x_pos, preds, color='red', s=200, zorder=4, marker='+',
               linewidths=3.5, label=label)

    ax.set_xlabel('Number of GFP Domains', fontsize=16)
    ax.set_ylabel('CoF Efficiency (%)', fontsize=16)
    ax.tick_params(axis='both', which='major', labelsize=14)
    ax.legend(loc='lower center', bbox_to_anchor=(0.5, 1.02), ncol=2,
              fontsize=10, frameon=True)
    ax.set_xlim(0.5, len(n_vals) + 0.5)
    ax.set_ylim(0, ylim)
    ax.set_xticks(x_pos)
    ax.set_xticklabels([str(n) for n in n_vals])

    plt.tight_layout()
    for fmt in ['png', 'svg']:
        fig.savefig(figures_dir / f'{save_name}.{fmt}', dpi=300,
                    bbox_inches='tight', facecolor='white', format=fmt)
    plt.close(fig)
    print(f"Saved: figures/{save_name}.png + .svg")


# =============================================================================
# MAIN EXECUTION
# =============================================================================
if __name__ == '__main__':

    print("=" * 60)
    print("  GEOMETRIC SPATIAL DELAY MODEL")
    print("=" * 60)

    # ── 1. Load experimental data ────────────────────────────────────────
    print("\nLoading per-cell CoF efficiency data from Excel...")

    sf_means, sf_sems, sf_cells = load_experimental_data(
        data_dir / 'Dark_mCh_Cells_new.xlsx'
    )
    print(f"  sfGFP: {sum(len(v) for v in sf_cells.values())} cells, "
          f"n_gfp = {sorted(sf_means.keys())}")

    uv_means, uv_sems, uv_cells = load_experimental_data(
        data_dir / 'Dark_mCh_Cells_slow.xlsx'
    )
    print(f"  GFPuv: {sum(len(v) for v in uv_cells.values())} cells, "
          f"n_gfp = {sorted(uv_means.keys())}")

    # ── 2. Fit both variants ─────────────────────────────────────────────
    result_sf = fit_model(sf_means, sf_sems, V_SF, 'sfGFP')
    result_uv = fit_model(uv_means, uv_sems, V_UV, 'GFPuv')

    # ── 3. Spatial constraints table ─────────────────────────────────────
    print("\n\n--- Spatial Constraints ---")
    print(f"{'Domain':<8} {'End (aa)':>10} {'Exit (aa)':>10} "
          f"{'Remaining (aa)':>15}")
    for i in range(N_GFP_MAX):
        remaining = L_TOTAL - X_EXIT[i]
        flag = " *** FAILS" if remaining <= 0 else ""
        print(f"GFP {i+1:<4} {X_END[i]:>10} {X_EXIT[i]:>10} "
              f"{remaining:>15}{flag}")

    for label, result in [('sfGFP', result_sf), ('GFPuv', result_uv)]:
        print(f"\n{label}: domains that can fold "
              f"(L_fold={result['L_fold']:.0f} aa):")
        for i in range(N_GFP_MAX):
            x_fl = X_EXIT[i] + result['L_fold']
            status = "✓ folds" if x_fl < L_TOTAL else "✗ runs out of mRNA"
            print(f"  GFP{i+1}: x_fluorescent = {x_fl:.0f} aa  →  {status}")

    # ── 4. Save data ─────────────────────────────────────────────────────
    # Spatial constraints CSV
    with open(data_dir / 'spatial_constraints.csv', 'w', newline='') as f:
        w = csv.writer(f)
        w.writerow(['domain', 'x_end_aa', 'x_exit_aa', 'remaining_aa',
                     'sfGFP_x_fluorescent_aa', 'sfGFP_can_fold',
                     'GFPuv_x_fluorescent_aa', 'GFPuv_can_fold'])
        for i in range(N_GFP_MAX):
            x_fl_sf = X_EXIT[i] + result_sf['L_fold']
            x_fl_uv = X_EXIT[i] + result_uv['L_fold']
            w.writerow([i + 1, X_END[i], X_EXIT[i], L_TOTAL - X_EXIT[i],
                         f'{x_fl_sf:.1f}', x_fl_sf < L_TOTAL,
                         f'{x_fl_uv:.1f}', x_fl_uv < L_TOTAL])
    print(f"\nSaved: data/spatial_constraints.csv")

    # Fit results CSV
    with open(data_dir / 'fit_results.csv', 'w', newline='') as f:
        w = csv.writer(f)
        w.writerow(['variant', 'v_aa_per_s', 'A_pct', 'tau_fold_s',
                     'L_fold_aa', 'r2', 'chi2'])
        for r in [result_sf, result_uv]:
            w.writerow([r['variant'], r['v'], f"{r['A']:.4f}",
                         f"{r['tau_fold']:.4f}", f"{r['L_fold']:.1f}",
                         f"{r['r2']:.4f}", f"{r['chi2']:.4f}"])
    print(f"Saved: data/fit_results.csv")

    # Predictions CSV
    with open(data_dir / 'predictions.csv', 'w', newline='') as f:
        w = csv.writer(f)
        w.writerow(['variant', 'n_gfp', 'observed_pct', 'sem_pct',
                     'predicted_pct', 'residual_pct'])
        for r in [result_sf, result_uv]:
            for n, obs, sem, pred in zip(r['n_vals'], r['obs'],
                                         r['sems'], r['preds']):
                w.writerow([r['variant'], n, f"{obs:.2f}", f"{sem:.2f}",
                             f"{pred:.2f}", f"{pred - obs:.2f}"])
    print(f"Saved: data/predictions.csv")

    # JSON (full machine-readable)
    with open(data_dir / 'geometric_model_results.json', 'w') as f:
        json.dump({'sfGFP': result_sf, 'GFPuv': result_uv,
                   'geometry': {'L_total': L_TOTAL, 'L_tunnel': L_TUNNEL,
                                'N_gfp_max': N_GFP_MAX,
                                'X_END': X_END, 'X_EXIT': X_EXIT}},
                  f, indent=2)
    print(f"Saved: data/geometric_model_results.json")

    # ── 5. Plot model fits ───────────────────────────────────────────────
    plot_geometric_fit(result_sf, sf_cells, 'geometric_model_fast_fit',
                       label='Geometric Model (fast)', ylim=100)
    plot_geometric_fit(result_uv, uv_cells, 'geometric_model_slow_fit',
                       label='Geometric Model (slow)', ylim=60)

    # ── 6. Parameter sensitivity analysis ────────────────────────────────
    print("\nComputing 2D parameter sensitivity...")
    ci_results = plot_sensitivity(result_sf, result_uv,
                                   sf_means, sf_sems, uv_means, uv_sems)

    # ── 7. Save parameter estimates with 95% CIs ────────────────────────
    with open(data_dir / 'parameter_estimates_with_ci.csv', 'w', newline='') as f:
        w = csv.writer(f)
        w.writerow(['variant', 'parameter', 'optimum', '95ci_low', '95ci_high'])
        for variant_key, ci in ci_results.items():
            w.writerow([variant_key, 'tau_fold (s)',
                        f"{ci['tau_fold_opt']:.1f}",
                        f"{ci['tau_fold_95ci_low']:.1f}",
                        f"{ci['tau_fold_95ci_high']:.1f}"])
            w.writerow([variant_key, 'A (%)',
                        f"{ci['A_opt']:.1f}",
                        f"{ci['A_95ci_low']:.1f}",
                        f"{ci['A_95ci_high']:.1f}"])
            w.writerow([variant_key, 'L_fold (aa)',
                        f"{ci['L_fold']:.0f}", '', ''])
            w.writerow([variant_key, 'k_e (aa/s)',
                        f"{ci['v']:.2f}", '', ''])
            w.writerow([variant_key, 'chi2',
                        f"{ci['chi2']:.2f}", '', ''])
    print(f"Saved: data/parameter_estimates_with_ci.csv")

    print("\n" + "=" * 60)
    print("  DONE")
    print("=" * 60)
